---
title: "R Notebook"
output: html_notebook
---

# What happens
- check if using x as a variables is useful
- bootstrap + chisq to check the results


```{r load}
d = read.csv("data3a.csv")
d
```

```{r fit}
fit1 = glm(y ~ 1, data = d, family = poisson)
fit2 = glm(y ~ x, data = d, family = poisson)
summary(fit1)

```

```{r deviance}
fit1$deviance - fit2$deviance
```

# Bootstrap
```{r functions}
get.dd = function(data){
        n.sample = nrow(data)
        y.mean = mean(data$y)
        data$y.rnd =rpois(n.sample, lambda = y.mean)
        fit1 = glm(y.rnd ~ 1, data = data, family = poisson)
        fit2 = glm(y.rnd ~ x, data = data, family = poisson)
        return(fit1$deviance - fit2$deviance)
}

pb = function(data, n.bootstrap){
        replicate(n.bootstrap, get.dd(data))
}

dd12 = pb(d, n.bootstrap = 1000)

```

# result 
```{r result}
summary(dd12)
{
hist(dd12, 100)
abline(v = 4.5, lty = 2)
}

sum(dd12 >= 4.5) /1000
quantile(dd12, 0.95)

```

# Chisq
```{r chisq}
fit1 = glm(y ~ 1, data = d, family = poisson)
fit2 = glm(y ~ x, data = d, family = poisson)

anova(fit1, fit2, test = "Chisq")

```

